Sticky videos
dtudk/pythonsupport-page pull request #45
Opened 2024-08-11 19:02 UTC by manufer20

Adds a picture-in-picture to the video. The code is optimized for one video per page, but can be changed to fit another requirements.

You can try how it works on docs/videotutorials/try-sticky-video.html

2024-08-15 16:58 UTC, TheWolf534 commented
Finalized picture-in-picture prototype for demonstration

2024-08-16 09:18 UTC, zerothi commented
Thanks for this @TheWolf534 lets finalize this next week! :)

2024-08-21 13:50 UTC, TheWolf534 commented
Now sticky videos work on all the videos and also when scrolling upwards

2024-08-26 06:45 UTC, zerothi requested changes
small changes, and a rebase would be required.

2024-08-26 06:45 UTC, zerothi commented on docs/conf.py
> +    app.add_js_file("sticky_video.js")
there is already an `setup` method, so I don't think this will do anything. At least I don't think it should be necessary.

2024-08-27 07:52 UTC, closed without merging